badge = "f"
artifact_url = "https://github.com/cispa/RISCy-cache-coherence"
cd = "c"
citation = "@inproceedings{Thomas2026Riscy,\n author = {Thomas, Fabian and Schwarz, Michael},\n booktitle = {{IEEE S\\&P}},\n title = {{RISCy Cache Coherence: Timer-Free Architectural Cache Attacks via Instruction/Data Cache Incoherence}},\n year = {2026}\n}"
license_url = "https://opensource.org/license/mit"
infrastructure_constraints = "The artifact requires specific CPU hardware."
infrastructure_access = "We provide evaluators with SSH access to lab88 (Qualcomm Oryon). Access details are provided via HotCRP comment."
install_script = "https://github.com/cispa/RISCy-cache-coherence"
use = "This artifact provides the code for all experiments of the paper and is intended as a library for supported systems. It is not guaranteed to be portable to arbitrary CPUs or microarchitectures."
destructive = "The artifact uses kernel modules to unlock privileged interfaces to the CPU. It is highly recommended to only use these modules on lab machines."
claim1 = "The I2SC library leaks D-cache state without timers."
script1 = "https://github.com/cispa/RISCy-cache-coherence/blob/main/ARTIFACT_EVALUATION.md"
expected1 = "The I2SC library leaks D-cache state without using a timer. See ARTIFACT_EVALUATION.md for details."
claim2 = "I2SC can be used to mount attacks, including practical timer-free Spectral attacks."
script2 = "https://github.com/cispa/RISCy-cache-coherence/blob/main/ARTIFACT_EVALUATION.md"
expected2 = "I2SC can be used for timer-free Spectral attacks. See ARTIFACT_EVALUATION.md for details."
hw = ""
gui = "n"
readme = "https://github.com/cispa/RISCy-cache-coherence/blob/main/ARTIFACT_EVALUATION.md"
sw = ""
api = ""
